url: ''
baseurl: ''
title: 'VTenchi Group'

plugins:
  - jekyll-postcss

postcss:
  cache: false

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - package-lock.json

staff_members:
  - { img: 'pum.png', name: 'Pum', quote: 'i want you to know that the very first 3d model i ever made was a centaur alien with huge booba, sculpted abs and a very...textured tongue. it was an accident. and it was a school project.' }
  - { img: 'pum.png', name: 'Pum', quote: 'i want you to know that the very first 3d model i ever made was a centaur alien with huge booba, sculpted abs and a very...textured tongue. it was an accident. and it was a school project.' }
  - { img: 'pum.png', name: 'Pum', quote: 'i want you to know that the very first 3d model i ever made was a centaur alien with huge booba, sculpted abs and a very...textured tongue. it was an accident. and it was a school project.' }
  - { img: 'pum.png', name: 'Pum', quote: 'i want you to know that the very first 3d model i ever made was a centaur alien with huge booba, sculpted abs and a very...textured tongue. it was an accident. and it was a school project.' }
  - { img: 'pum.png', name: 'Pum', quote: 'i want you to know that the very first 3d model i ever made was a centaur alien with huge booba, sculpted abs and a very...textured tongue. it was an accident. and it was a school project.' }
  - { img: 'pum.png', name: 'Pum', quote: 'i want you to know that the very first 3d model i ever made was a centaur alien with huge booba, sculpted abs and a very...textured tongue. it was an accident. and it was a school project.' }
